name: Linting and testing project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing yarn
        run: npm install --global yarn@1.22.19
      - name: Installing packages
        run: yarn install
      - name: Build production project
        run: yarn build:prod
      - name: Llinting typescript
        if: always() 
        run: yarn lint
      - name: Linting styles
        if: always() 
        run: yarn lint:scss
      - name: Running unit tests
        if: always() 
        run: yarn test
      


